language: python
python:
  - "2.7"
  - "pypy"  # PyPy2 5.8.0
install:
  - pip install -r requirements.txt
  - pip install nose
before_script:
  export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  nosetests SEC_Code/Python/Tests/
